### ISSUE TITLE
Link to the online game.

### ISSUE THREAD

**Issue by Nerwosolek** [psimm/businessgame#1]
Hi!
The link to the online game seems no longer valid.

**Comment by psimm** [comment]
Hi, thanks for reaching out!
You're right, the game is currently offline because it was consuming too many use hours on ShinyApps.io. Sorry! I'll put it back online once I have more resources for that. In the meantime you can play the game by cloning the repo and running it locally :)

**Comment by Nerwosolek** [comment]
Sure thing - totally understandable. I am going to run it locally, I am interested in business simulation games and did some prototype of it in JS.
